const trendingMovies = {
    "page": 1,
    "results": [{
        "adult": false,
        "backdrop_path": "/u17VLZqWFbeJsj1HpvB6QOOHvlC.jpg",
        "genre_ids": [Array],
        "id": 455476,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Knights of the Zodiac",
        "overview": "When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?",
        "popularity": 445.679,
        "poster_path": "/qW4crfED8mpNDadSmMdi7ZDzhXF.jpg",
        "release_date": "2023-04-27",
        "title": "Knights of the Zodiac",
        "video": false,
        "vote_average": 6.545,
        "vote_count": 202
    }, {
        "adult": false,
        "backdrop_path": "/zPcuuhwZFDzBTc66wtrLZ2qX5y4.jpg",
        "genre_ids": [Array],
        "id": 335977,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Indiana Jones and the Dial of Destiny",
        "overview": "Finding himself in a new era, approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
        "popularity": 507.767,
        "poster_path": "/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
        "release_date": "2023-06-28",
        "title": "Indiana Jones and the Dial of Destiny",
        "video": false,
        "vote_average": 6.5,
        "vote_count": 125
    }, {
        "adult": false,
        "backdrop_path": "/4QpKxH614YFIsmiIBVUbsnG2H8w.jpg",
        "genre_ids": [Array],
        "id": 961323,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Nimona",
        "overview": "A knight framed for a tragic crime teams with a scrappy, shape-shifting teen to prove his innocence. But what if she's the monster he's sworn to destroy?",
        "popularity": 32.65,
        "poster_path": "/dHFUte9BLYhihC9YqKWyxmWXnZu.jpg",
        "release_date": "2023-06-23",
        "title": "Nimona",
        "video": false,
        "vote_average": 8.3,
        "vote_count": 7
    }, {
        "adult": false,
        "backdrop_path": "/37LyKFPr7ksoXMea7MIWFa8Llaj.jpg",
        "genre_ids": [Array],
        "id": 714669,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Run Rabbit Run",
        "overview": "Sarah is a fertility doctor with a firm understanding of the cycle of life. When she is forced to make sense of the increasingly strange behavior of her young daughter Mia, she must challenge her own beliefs and confront a ghost from her past.",
        "popularity": 25.474,
        "poster_path": "/n34lYVoFy1C2lc02i7eaZFWznuN.jpg",
        "release_date": "2023-01-19",
        "title": "Run Rabbit Run",
        "video": false,
        "vote_average": 6.389,
        "vote_count": 27
    }, {
        "adult": false,
        "backdrop_path": "/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg",
        "genre_ids": [Array],
        "id": 569094,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Spider-Man: Across the Spider-Verse",
        "overview": "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
        "popularity": 1786.715,
        "poster_path": "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        "release_date": "2023-05-31",
        "title": "Spider-Man: Across the Spider-Verse",
        "video": false,
        "vote_average": 8.563,
        "vote_count": 1870
    }, {
        "adult": false,
        "backdrop_path": "/e2Jd0sYMCe6qvMbswGQbM0Mzxt0.jpg",
        "genre_ids": [Array],
        "id": 385687,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Fast X",
        "overview": "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
        "popularity": 3811.029,
        "poster_path": "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
        "release_date": "2023-05-17",
        "title": "Fast X",
        "video": false,
        "vote_average": 7.3,
        "vote_count": 2209
    }, {
        "adult": false,
        "backdrop_path": "/nniZPBIfrep9wbx0l1529RHXeD8.jpg",
        "genre_ids": [Array],
        "id": 502356,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "The Super Mario Bros. Movie",
        "overview": "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
        "popularity": 1457.516,
        "poster_path": "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
        "release_date": "2023-04-05",
        "title": "The Super Mario Bros. Movie",
        "video": false,
        "vote_average": 7.797,
        "vote_count": 5248
    }, {
        "adult": false,
        "backdrop_path": "/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg",
        "genre_ids": [Array],
        "id": 976573,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Elemental",
        "overview": "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
        "popularity": 1085.659,
        "poster_path": "/8riWcADI1ekEiBguVB9vkilhiQm.jpg",
        "release_date": "2023-06-14",
        "title": "Elemental",
        "video": false,
        "vote_average": 7.447,
        "vote_count": 246
    }, {
        "adult": false,
        "backdrop_path": "/uvjI5xzMv7ZBYPWnt9nGXUa2v4u.jpg",
        "genre_ids": [Array],
        "id": 1136736,
        "media_type": "movie",
        "original_language": "hi",
        "original_title": "Lust Stories 2",
        "overview": "Four eminent Indian directors explore sex, desire and love through short films in this sequel to 2018's Emmy-nominated 'Lust Stories'.",
        "popularity": 43.014,
        "poster_path": "/p5x729JI6wZs9hCqX7tc7oH87ih.jpg",
        "release_date": "2023-06-29",
        "title": "Lust Stories 2",
        "video": false,
        "vote_average": 5.5,
        "vote_count": 6
    }, {
        "adult": false,
        "backdrop_path": "/4pNlHx6ytdYBDs94PgcS0wQkbc4.jpg",
        "genre_ids": [Array],
        "id": 76600,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Avatar: The Way of Water",
        "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
        "popularity": 822.852,
        "poster_path": "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        "release_date": "2022-12-14",
        "title": "Avatar: The Way of Water",
        "video": false,
        "vote_average": 7.68,
        "vote_count": 8897
    }, {
        "adult": false,
        "backdrop_path": "/fhquRW28vRZHr26orSaFFnhYIA0.jpg",
        "genre_ids": [Array],
        "id": 697843,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Extraction 2",
        "overview": "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
        "popularity": 2001.538,
        "poster_path": "/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
        "release_date": "2023-06-09",
        "title": "Extraction 2",
        "video": false,
        "vote_average": 7.642,
        "vote_count": 1005
    }, {
        "adult": false,
        "backdrop_path": "/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg",
        "genre_ids": [Array],
        "id": 603692,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "John Wick: Chapter 4",
        "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
        "popularity": 1715.856,
        "poster_path": "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        "release_date": "2023-03-22",
        "title": "John Wick: Chapter 4",
        "video": false,
        "vote_average": 7.861,
        "vote_count": 3401
    }, {
        "adult": false,
        "backdrop_path": "/fEe2csLOUsTyaLdCccVJfFeJzhx.jpg",
        "genre_ids": [Array],
        "id": 298618,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "The Flash",
        "overview": "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
        "popularity": 844.898,
        "poster_path": "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
        "release_date": "2023-06-13",
        "title": "The Flash",
        "video": false,
        "vote_average": 6.73,
        "vote_count": 679
    }, {
        "adult": false,
        "backdrop_path": "/euO884625eFLfKLoc0MtFs5QiOS.jpg",
        "genre_ids": [Array],
        "id": 1070802,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Confidential Informant",
        "overview": "During a crack epidemic two narcotics agents hunting for a cop killer. Hoping for leads, Moran and Thorton pay off a junkie informant. To provide for his wife and son, Moran involves the stool pigeon in a deadly scheme. This causes the partners to come under the scrutiny of a suspicious internal affairs agent.",
        "popularity": 54.195,
        "poster_path": "/kCyAyqF6TKylJFuddaHtqq20b62.jpg",
        "release_date": "2023-06-30",
        "title": "Confidential Informant",
        "video": false,
        "vote_average": 5.5,
        "vote_count": 1
    }, {
        "adult": false,
        "backdrop_path": "/jQbnhNvFQXO7jwLzdrceCTspEeI.jpg",
        "genre_ids": [Array],
        "id": 346698,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Barbie",
        "overview": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        "popularity": 291.12,
        "poster_path": "/cgYg04miVQUAG2FKk3amSnnHzOp.jpg",
        "release_date": "2023-07-19",
        "title": "Barbie",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/14GEZCzCGhV7FMFaWi4Ec22Kcai.jpg",
        "genre_ids": [Array],
        "id": 459003,
        "media_type": "movie",
        "original_language": "uk",
        "original_title": "Мавка: Лісова пісня",
        "overview": "Mavka — a Soul of the Forest and its Warden — faces an impossible choice between love and her duty as guardian to the Heart of the Forest, when she falls in love with a human — the talented young musician Lukas.",
        "popularity": 32.896,
        "poster_path": "/eeJjd9JU2Mdj9d7nWRFLWlrcExi.jpg",
        "release_date": "2023-03-02",
        "title": "Mavka: The Forest Song",
        "video": false,
        "vote_average": 7,
        "vote_count": 31
    }, {
        "adult": false,
        "backdrop_path": "/7fN5rEBcRoylG3oZPZl1Qe6y7UV.jpg",
        "genre_ids": [Array],
        "id": 575264,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Mission: Impossible - Dead Reckoning Part One",
        "overview": "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the fate of the world at stake, and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan is forced to consider that nothing can matter more than his mission – not even the lives of those he cares about most.",
        "popularity": 132.624,
        "poster_path": "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
        "release_date": "2023-07-08",
        "title": "Mission: Impossible - Dead Reckoning Part One",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/ioCuhiUs0SW5UgembG0UiQZWPLY.jpg",
        "genre_ids": [Array],
        "id": 1040148,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Ruby Gillman, Teenage Kraken",
        "overview": "A shy teenager discovers that she's part of a legendary royal lineage of mythical sea krakens and that her destiny, in the depths of the oceans, is bigger than she ever dreamed.",
        "popularity": 209.498,
        "poster_path": "/lotWiuWuTGlQ94rzBdy6ZmKZnTA.jpg",
        "release_date": "2023-06-28",
        "title": "Ruby Gillman, Teenage Kraken",
        "video": false,
        "vote_average": 6.7,
        "vote_count": 8
    }, {
        "adult": false,
        "backdrop_path": "/mmSSn8Yn3GbJv9MsSnD4J1LnN9l.jpg",
        "genre_ids": [Array],
        "id": 988078,
        "media_type": "movie",
        "original_language": "es",
        "original_title": "A través del mar",
        "overview": "After a year of long-distance, Raquel and Ares reunite on a steamy beach trip. Faced with fresh flirtations and insecurities, will their love prevail?",
        "popularity": 554.739,
        "poster_path": "/dAyJqJ8KoglZysttC6BfVmDFQUt.jpg",
        "release_date": "2023-06-23",
        "title": "Through My Window: Across the Sea",
        "video": false,
        "vote_average": 6.699,
        "vote_count": 254
    }, {
        "adult": false,
        "backdrop_path": "/nBEFrdcVhwceGSFw83RksxY9Blg.jpg",
        "genre_ids": [Array],
        "id": 649609,
        "media_type": "movie",
        "original_language": "en",
        "original_title": "Renfield",
        "overview": "Having grown sick and tired of his centuries as Dracula's lackey, Renfield finds a new lease on life — and maybe even redemption — when he falls for feisty, perennially angry traffic cop Rebecca Quincy.",
        "popularity": 209.305,
        "poster_path": "/2OaprROMZZeiWsydjGUIkXrv2Z3.jpg",
        "release_date": "2023-04-07",
        "title": "Renfield",
        "video": false,
        "vote_average": 6.84,
        "vote_count": 723
    }],
    "total_pages": 1000,
    "total_results": 20000
};

const upcomingMovies = {
    "dates": {"maximum": "2023-07-25", "minimum": "2023-07-06"},
    "page": 1,
    "results": [{
        "adult": false,
        "backdrop_path": "/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg",
        "genre_ids": [Array],
        "id": 976573,
        "original_language": "en",
        "original_title": "Elemental",
        "overview": "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
        "popularity": 1085.659,
        "poster_path": "/8riWcADI1ekEiBguVB9vkilhiQm.jpg",
        "release_date": "2023-06-14",
        "title": "Elemental",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 239
    }, {
        "adult": false,
        "backdrop_path": "/fEe2csLOUsTyaLdCccVJfFeJzhx.jpg",
        "genre_ids": [Array],
        "id": 298618,
        "original_language": "en",
        "original_title": "The Flash",
        "overview": "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
        "popularity": 844.898,
        "poster_path": "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
        "release_date": "2023-06-13",
        "title": "The Flash",
        "video": false,
        "vote_average": 6.7,
        "vote_count": 673
    }, {
        "adult": false,
        "backdrop_path": "/vQ5T84t8h4N2xAswNFW9fkVIyZq.jpg",
        "genre_ids": [Array],
        "id": 536437,
        "original_language": "en",
        "original_title": "Hypnotic",
        "overview": "A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.",
        "popularity": 775.384,
        "poster_path": "/3IhGkkalwXguTlceGSl8XUJZOVI.jpg",
        "release_date": "2023-05-11",
        "title": "Hypnotic",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 256
    }, {
        "adult": false,
        "backdrop_path": "/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg",
        "genre_ids": [Array],
        "id": 890771,
        "original_language": "en",
        "original_title": "The Black Demon",
        "overview": "Oilman Paul Sturges' idyllic family vacation turns into a nightmare when they encounter a ferocious megalodon shark that will stop at nothing to protect its territory. Stranded and under constant attack, Paul and his family must somehow find a way to get his family back to shore alive before it strikes again in this epic battle between humans and nature.",
        "popularity": 681.317,
        "poster_path": "/uiFcFIjig0YwyNmhoxkxtAAVIL2.jpg",
        "release_date": "2023-04-26",
        "title": "The Black Demon",
        "video": false,
        "vote_average": 6.3,
        "vote_count": 241
    }, {
        "adult": false,
        "backdrop_path": "/94TIUEhuwv8PhdIADEvSuwPljS5.jpg",
        "genre_ids": [Array],
        "id": 840326,
        "original_language": "fi",
        "original_title": "Sisu",
        "overview": "Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.",
        "popularity": 506.635,
        "poster_path": "/ygO9lowFMXWymATCrhoQXd6gCEh.jpg",
        "release_date": "2023-01-27",
        "title": "Sisu",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 803
    }, {
        "adult": false,
        "backdrop_path": "/bJFKGpUbSFSoXcIZcAgtAi3rtc7.jpg",
        "genre_ids": [Array],
        "id": 758323,
        "original_language": "en",
        "original_title": "The Pope's Exorcist",
        "overview": "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
        "popularity": 466.801,
        "poster_path": "/gNPqcv1tAifbN7PRNgqpzY8sEJZ.jpg",
        "release_date": "2023-04-05",
        "title": "The Pope's Exorcist",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 1493
    }, {
        "adult": false,
        "backdrop_path": "/cKE9qZqYtF4jimf0GFOqKfy7NEU.jpg",
        "genre_ids": [Array],
        "id": 884605,
        "original_language": "en",
        "original_title": "No Hard Feelings",
        "overview": "On the brink of losing her childhood home, Maddie discovers an intriguing job listing: wealthy helicopter parents looking for someone to “date” their introverted 19-year-old son, Percy, before he leaves for college. To her surprise, Maddie soon discovers the awkward Percy is no sure thing.",
        "popularity": 355.526,
        "poster_path": "/5xeNPGbM8ImVdJACUoGpXT8Pxx3.jpg",
        "release_date": "2023-06-15",
        "title": "No Hard Feelings",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 87
    }, {
        "adult": false,
        "backdrop_path": "/jAmmb9RApuRckDJtYWeOgBUgQyG.jpg",
        "genre_ids": [Array],
        "id": 893712,
        "original_language": "ja",
        "original_title": "劇場版 ソードアート・オンライン -プログレッシブ- 冥き夕闇のスケルツォ",
        "overview": "Over a ers were trapped inside the \"Sword Art Online\" world. Asuna, who cleared the first floor of the floating iron castle of Aincrad, joined up with Kirito and continued her journey to reach the top floor. With the support of female Information Broker Argo, clearing the floors seemed to be progressing smoothly, but conflict erupts between two major guilds who should be working together – the top player groups ALS (the Aincrad Liberation Squad) and DKB (the Dragon Knights Brigade). And meanwhile, behind the scenes exists a mysterious figure pulling the strings…",
        "popularity": 304.1,
        "poster_path": "/2lEyzOq6ILNgBpLLpTRckQhbNNt.jpg",
        "release_date": "2022-10-22",
        "title": "Sword Art Online the Movie -Progressive- Scherzo of Deep Night",
        "video": false,
        "vote_average": 7.6,
        "vote_count": 89
    }, {
        "adult": false,
        "backdrop_path": "/jQbnhNvFQXO7jwLzdrceCTspEeI.jpg",
        "genre_ids": [Array],
        "id": 346698,
        "original_language": "en",
        "original_title": "Barbie",
        "overview": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        "popularity": 291.12,
        "poster_path": "/cgYg04miVQUAG2FKk3amSnnHzOp.jpg",
        "release_date": "2023-07-19",
        "title": "Barbie",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/pDihgK7EGrSHZ4E5Wa8GkPaibXA.jpg",
        "genre_ids": [Array],
        "id": 605886,
        "original_language": "en",
        "original_title": "Misanthrope",
        "overview": "Baltimore. New Year's Eve. A talented but troubled police officer is recruited by the FBI's chief investigator to help profile and track down a mass murderer.",
        "popularity": 287.226,
        "poster_path": "/mFp3l4lZg1NSEsyxKrdi0rNK8r1.jpg",
        "release_date": "2023-04-06",
        "title": "To Catch a Killer",
        "video": false,
        "vote_average": 6.8,
        "vote_count": 294
    }, {
        "adult": false,
        "backdrop_path": "/ceYZCBfwbBwSpGJ6PapNVw5jqLG.jpg",
        "genre_ids": [Array],
        "id": 916224,
        "original_language": "ja",
        "original_title": "すずめの戸締まり",
        "overview": "Suzume, 17,r mother as a little girl. On her way to school, she meets a mysterious young man. But her curiosity unleashes a calamity that endangers the entire population of Japan, and so Suzume embarks on a journey to set things right.",
        "popularity": 240.591,
        "poster_path": "/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg",
        "release_date": "2022-11-11",
        "title": "Suzume",
        "video": false,
        "vote_average": 7.9,
        "vote_count": 445
    }, {
        "adult": false,
        "backdrop_path": "/jOkXeuLo4MBMpeoMa1ClAfTkxuI.jpg",
        "genre_ids": [Array],
        "id": 614479,
        "original_language": "en",
        "original_title": "Insidious: The Red Door",
        "overview": "To put their demons to rest once and for all, Josh Lambert and a college-aged Dalton Lambert must go deeper into The Further than ever before, facing their family's dark past and a host of new and more horrifying terrors that lurk behind the red door.",
        "popularity": 225.371,
        "poster_path": "/azTC5osYiqei1ofw6Z3GmUrxQbi.jpg",
        "release_date": "2023-06-16",
        "title": "Insidious: The Red Door",
        "video": false,
        "vote_average": 8.9,
        "vote_count": 6
    }, {
        "adult": false,
        "backdrop_path": "/ioCuhiUs0SW5UgembG0UiQZWPLY.jpg",
        "genre_ids": [Array],
        "id": 1040148,
        "original_language": "en",
        "original_title": "Ruby Gillman, Teenage Kraken",
        "overview": "A shy teenager discovers that she's part of a legendary royal lineage of mythical sea krakens and that her destiny, in the depths of the oceans, is bigger than she ever dreamed.",
        "popularity": 209.498,
        "poster_path": "/lotWiuWuTGlQ94rzBdy6ZmKZnTA.jpg",
        "release_date": "2023-06-28",
        "title": "Ruby Gillman, Teenage Kraken",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 6
    }, {
        "adult": false,
        "backdrop_path": "/1PQqvw7wnGeWqvXcBLaGK46n0zk.jpg",
        "genre_ids": [Array],
        "id": 496450,
        "original_language": "fr",
        "original_title": "Miraculous - le film",
        "overview": "A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.",
        "popularity": 177.795,
        "poster_path": "/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg",
        "release_date": "2023-07-05",
        "title": "Miraculous: Ladybug & Cat Noir, The Movie",
        "video": false,
        "vote_average": 9.5,
        "vote_count": 4
    }, {
        "adult": false,
        "backdrop_path": "/baLw3zvl9R31Ocxh7uIpkk5cLVx.jpg",
        "genre_ids": [Array],
        "id": 893345,
        "original_language": "en",
        "original_title": "The Secret Kingdom",
        "overview": "Verity and Peter’s trip to the old family mansion takes a turn when the floor of their room suddenly gives way and they fall into an underground chamber where they are met by a civilization of creatures. The leader tells them that Peter's arrival was foretold as he’s the one who can use Great Clock of the Citadel to restart time and destroy the Shroud, a malevolent creature who feeds on fear itself...",
        "popularity": 175.757,
        "poster_path": "/dteXMzVY53GBHUgrR7vigAartsP.jpg",
        "release_date": "2023-04-27",
        "title": "The Secret Kingdom",
        "video": false,
        "vote_average": 7,
        "vote_count": 23
    }, {
        "adult": false,
        "backdrop_path": "/lQzSMhkAl90iXPirjnLbRHkxApC.jpg",
        "genre_ids": [Array],
        "id": 917007,
        "original_language": "en",
        "original_title": "Bed Rest",
        "overview": "A pregnant woman on bed rest begins to wonder if her house is haunted or if it's all in her head.",
        "popularity": 154.535,
        "poster_path": "/tiZF8b9T9fMcwvsEEkJ5ik1wCnV.jpg",
        "release_date": "2022-12-08",
        "title": "Bed Rest",
        "video": false,
        "vote_average": 6.6,
        "vote_count": 56
    }, {
        "adult": false,
        "backdrop_path": "/7fN5rEBcRoylG3oZPZl1Qe6y7UV.jpg",
        "genre_ids": [Array],
        "id": 575264,
        "original_language": "en",
        "original_title": "Mission: Impossible - Dead Reckoning Part One",
        "overview": "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the fate of the world at stake, and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan is forced to consider that nothing can matter more than his mission – not even the lives of those he cares about most.",
        "popularity": 132.624,
        "poster_path": "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
        "release_date": "2023-07-08",
        "title": "Mission: Impossible - Dead Reckoning Part One",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg",
        "genre_ids": [Array],
        "id": 862,
        "original_language": "en",
        "original_title": "Toy Story",
        "overview": "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
        "popularity": 108.304,
        "poster_path": "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
        "release_date": "1995-10-30",
        "title": "Toy Story",
        "video": false,
        "vote_average": 8,
        "vote_count": 16823
    }, {
        "adult": false,
        "backdrop_path": "/gGZxCy9keK0D6TxbmS8GJj85Ut4.jpg",
        "genre_ids": [Array],
        "id": 809787,
        "original_language": "en",
        "original_title": "Mafia Mamma",
        "overview": "A suburban American woman inherits her grandfather’s Mafia empire and, guided by the Firm’s trusted consigliere, defies everyone’s expectations, including her own, as the new head of the family business.",
        "popularity": 99.911,
        "poster_path": "/zi0Lrmtvhrz52VXUjwEKlXItF9q.jpg",
        "release_date": "2023-04-13",
        "title": "Mafia Mamma",
        "video": false,
        "vote_average": 6.6,
        "vote_count": 75
    }, {
        "adult": false,
        "backdrop_path": "/9dZ52zOs91RMgjjORoMIi6VGNLr.jpg",
        "genre_ids": [Array],
        "id": 872585,
        "original_language": "en",
        "original_title": "Oppenheimer",
        "overview": "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
        "popularity": 97.543,
        "poster_path": "/aqZ75oN6yd7UTShYIMNlpSdDbbH.jpg",
        "release_date": "2023-07-19",
        "title": "Oppenheimer",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }],
    "total_pages": 15,
    "total_results": 289
};

const movieCredits = {
    "cast": [{
        "adult": false,
        "cast_id": 1,
        "character": "Julie Rivers",
        "credit_id": "61bc3df23f8ede001df18d55",
        "gender": 1,
        "id": 1373659,
        "known_for_department": "Acting",
        "name": "Melissa Barrera",
        "order": 0,
        "original_name": "Melissa Barrera",
        "popularity": 39.46,
        "profile_path": "/yiAFCOj72iI82e3UPgpQXmefaFI.jpg"
    }, {
        "adult": false,
        "cast_id": 2,
        "character": "Daniel Rivers",
        "credit_id": "61bc3dfb1f3319008d4677bb",
        "gender": 2,
        "id": 545195,
        "known_for_department": "Acting",
        "name": "Guy Burnet",
        "order": 1,
        "original_name": "Guy Burnet",
        "popularity": 10.483,
        "profile_path": "/zwzQ48PvIiorkDopCljnASEO6FS.jpg"
    }, {
        "adult": false,
        "cast_id": 6,
        "character": "Delmy Walker",
        "credit_id": "62c014f263d713026c2eaf5b",
        "gender": 1,
        "id": 1590230,
        "known_for_department": "Acting",
        "name": "Edie Inksetter",
        "order": 2,
        "original_name": "Edie Inksetter",
        "popularity": 4.898,
        "profile_path": "/kIJVcF4YYMS4UQFqrSIZyGYpRPq.jpg"
    }, {
        "adult": false,
        "cast_id": 27,
        "character": "Four-year-old Kinsey",
        "credit_id": "645e43939590e301695e5b45",
        "gender": 2,
        "id": 1975740,
        "known_for_department": "Acting",
        "name": "Sebastian Billingsley-Rodriguez",
        "order": 3,
        "original_name": "Sebastian Billingsley-Rodriguez",
        "popularity": 6.411,
        "profile_path": "/xhPHlfkz0RgoUGDfMpvz2SCYMlf.jpg"
    }, {
        "adult": false,
        "cast_id": 7,
        "character": "Dr. Meadows",
        "credit_id": "62c014fdaf6e9410ac3e984b",
        "gender": 2,
        "id": 1303813,
        "known_for_department": "Acting",
        "name": "Erik Athavale",
        "order": 4,
        "original_name": "Erik Athavale",
        "popularity": 7.579,
        "profile_path": "/v5J8qSMldAixR3PcUoQmbAPlOOM.jpg"
    }, {
        "adult": false,
        "cast_id": 9,
        "character": "Melandra Kinsey",
        "credit_id": "62c015170bb0760dcb649de2",
        "gender": 1,
        "id": 1661385,
        "known_for_department": "Crew",
        "name": "Kristen Sawatzky",
        "order": 5,
        "original_name": "Kristen Sawatzky",
        "popularity": 5.832,
        "profile_path": "/m4seR2YH0BmJPPzVpe8tqoPmEr7.jpg"
    }, {
        "adult": false,
        "cast_id": 19,
        "character": "Seven-year-old Kinsey",
        "credit_id": "62e5bea546e75f006ed8b43a",
        "gender": 2,
        "id": 2867971,
        "known_for_department": "Acting",
        "name": "Koen Schneiderat",
        "order": 6,
        "original_name": "Koen Schneiderat",
        "popularity": 1.676,
        "profile_path": "/a7N0SVIGrKqAEt8IiyuUuIH2qGn.jpg"
    }, {
        "adult": false,
        "cast_id": 8,
        "character": "Dean Whittier",
        "credit_id": "62c0150a9672ed007ee9901f",
        "gender": 2,
        "id": 1128538,
        "known_for_department": "Acting",
        "name": "Paul Essiembre",
        "order": 7,
        "original_name": "Paul Essiembre",
        "popularity": 6.353,
        "profile_path": "/cM9uhNoWtNBfjVpmESoL0HJf9UX.jpg"
    }, {
        "adult": false,
        "cast_id": 21,
        "character": "Mrs. Whittier",
        "credit_id": "63b64194904f6d00919f7f60",
        "gender": 1,
        "id": 61160,
        "known_for_department": "Acting",
        "name": "Marina Stephenson Kerr",
        "order": 8,
        "original_name": "Marina Stephenson Kerr",
        "popularity": 3.584,
        "profile_path": "/sLEOfwtdFCzpemIhOmpB1xpz6p0.jpg"
    }, {
        "adult": false,
        "cast_id": 11,
        "character": "Clinic Nurse",
        "credit_id": "62c015351056110d2d439345",
        "gender": 1,
        "id": 3608818,
        "known_for_department": "Acting",
        "name": "Diana Botelho-Urbanski",
        "order": 9,
        "original_name": "Diana Botelho-Urbanski",
        "popularity": 0.6,
        "profile_path": null
    }, {
        "adult": false,
        "cast_id": 5,
        "character": "OB-GYN",
        "credit_id": "62c014e822e4800fa5c20970",
        "gender": 1,
        "id": 212141,
        "known_for_department": "Acting",
        "name": "Kristen Harris",
        "order": 10,
        "original_name": "Kristen Harris",
        "popularity": 10.235,
        "profile_path": "/jbu0VJaJtw0awZ9J6ObAQiIcG8s.jpg"
    }, {
        "adult": false,
        "cast_id": 24,
        "character": "Nurse",
        "credit_id": "63cab741bb070d007c81359f",
        "gender": 1,
        "id": 2154533,
        "known_for_department": "Acting",
        "name": "Stephanie Sy",
        "order": 11,
        "original_name": "Stephanie Sy",
        "popularity": 6.051,
        "profile_path": "/o2LxSIY7kbSh8WNpnM0FOPP6CVK.jpg"
    }, {
        "adult": false,
        "cast_id": 22,
        "character": "ER Doctor",
        "credit_id": "63b641aa8ee49c008b27253c",
        "gender": 2,
        "id": 1148697,
        "known_for_department": "Acting",
        "name": "Adam Hurtig",
        "order": 12,
        "original_name": "Adam Hurtig",
        "popularity": 5.962,
        "profile_path": "/nLOpEqGZkalzE74sXP3JMx4oq43.jpg"
    }, {
        "adult": false,
        "cast_id": 25,
        "character": "ER Nurse",
        "credit_id": "63cab7610398ab00af066673",
        "gender": 1,
        "id": 1929450,
        "known_for_department": "Acting",
        "name": "Ava Julien",
        "order": 13,
        "original_name": "Ava Julien",
        "popularity": 1.168,
        "profile_path": null
    }, {
        "adult": false,
        "cast_id": 28,
        "character": "Jake",
        "credit_id": "645e43e788b1480158f2de10",
        "gender": 2,
        "id": 117051,
        "known_for_department": "Acting",
        "name": "Darcy Fehr",
        "order": 14,
        "original_name": "Darcy Fehr",
        "popularity": 3.744,
        "profile_path": "/pNFSuPYFL74PsBMzzVE1A3IHEx6.jpg"
    }, {
        "adult": false,
        "cast_id": 29,
        "character": "Foreman",
        "credit_id": "645e43f7aafebd018b692bcf",
        "gender": 2,
        "id": 83853,
        "known_for_department": "Acting",
        "name": "Arne MacPherson",
        "order": 15,
        "original_name": "Arne MacPherson",
        "popularity": 2.127,
        "profile_path": null
    }, {
        "adult": false,
        "cast_id": 23,
        "character": "Remediation Worker",
        "credit_id": "63cab73003f0b600a0792e95",
        "gender": 2,
        "id": 1356237,
        "known_for_department": "Acting",
        "name": "Jean-Jacques Javier",
        "order": 16,
        "original_name": "Jean-Jacques Javier",
        "popularity": 1.553,
        "profile_path": "/pb26xUVUqxpjR8YCGawAX5zdL9a.jpg"
    }, {
        "adult": false,
        "cast_id": 30,
        "character": "Paramedic",
        "credit_id": "645e4403ef8b32011b46d32e",
        "gender": 1,
        "id": 2188034,
        "known_for_department": "Acting",
        "name": "Stephanie Moroz",
        "order": 17,
        "original_name": "Stephanie Moroz",
        "popularity": 4.261,
        "profile_path": "/vePDX1RSUY2MtvfA96Y9UHJNjBQ.jpg"
    }],
    "crew": [{
        "adult": false,
        "credit_id": "62c01590f1b5710059a88c35",
        "department": "Production",
        "gender": 2,
        "id": 20204,
        "job": "Producer",
        "known_for_department": "Writing",
        "name": "James Vanderbilt",
        "original_name": "James Vanderbilt",
        "popularity": 10.141,
        "profile_path": "/tptj363x29gJ6hfTWBwBnWQG7A.jpg"
    }, {
        "adult": false,
        "credit_id": "62c0157c924ce6004cb200e2",
        "department": "Production",
        "gender": 2,
        "id": 61122,
        "job": "Producer",
        "known_for_department": "Production",
        "name": "William Sherak",
        "original_name": "William Sherak",
        "popularity": 2.43,
        "profile_path": "/lOh6jL1NKoCbaNZgRF0VMkwT0xb.jpg"
    }, {
        "adult": false,
        "credit_id": "62c01552af6e9410ab449bc2",
        "department": "Production",
        "gender": 1,
        "id": 1373659,
        "job": "Producer",
        "known_for_department": "Acting",
        "name": "Melissa Barrera",
        "original_name": "Melissa Barrera",
        "popularity": 39.46,
        "profile_path": "/yiAFCOj72iI82e3UPgpQXmefaFI.jpg"
    }, {
        "adult": false,
        "credit_id": "645bacb9156cc7015e78825b",
        "department": "Camera",
        "gender": 2,
        "id": 1397788,
        "job": "Director of Photography",
        "known_for_department": "Camera",
        "name": "Jean-Philippe Bernier",
        "original_name": "Jean-Philippe Bernier",
        "popularity": 1.277,
        "profile_path": null
    }, {
        "adult": false,
        "credit_id": "61bc3e0de72fe80040dcce2d",
        "department": "Directing",
        "gender": 0,
        "id": 2198345,
        "job": "Director",
        "known_for_department": "Writing",
        "name": "Lori Evans Taylor",
        "original_name": "Lori Evans Taylor",
        "popularity": 2.507,
        "profile_path": null
    }, {
        "adult": false,
        "credit_id": "62c0155faf6e9410aa738efb",
        "department": "Production",
        "gender": 0,
        "id": 2198345,
        "job": "Producer",
        "known_for_department": "Writing",
        "name": "Lori Evans Taylor",
        "original_name": "Lori Evans Taylor",
        "popularity": 2.507,
        "profile_path": null
    }, {
        "adult": false,
        "credit_id": "62c16ee20bb07617a6f9a450",
        "department": "Writing",
        "gender": 0,
        "id": 2198345,
        "job": "Writer",
        "known_for_department": "Writing",
        "name": "Lori Evans Taylor",
        "original_name": "Lori Evans Taylor",
        "popularity": 2.507,
        "profile_path": null
    }, {
        "adult": false,
        "credit_id": "62c014bf1056110d2bc1e463",
        "department": "Crew",
        "gender": 0,
        "id": 2198345,
        "job": "Script",
        "known_for_department": "Writing",
        "name": "Lori Evans Taylor",
        "original_name": "Lori Evans Taylor",
        "popularity": 2.507,
        "profile_path": null
    }, {
        "adult": false,
        "credit_id": "62c0156e924ce6007c9d3792",
        "department": "Production",
        "gender": 2,
        "id": 2564279,
        "job": "Producer",
        "known_for_department": "Production",
        "name": "Paul Neinstein",
        "original_name": "Paul Neinstein",
        "popularity": 1.216,
        "profile_path": "/6oVqQswuGkDLFpKIvFXvVThC8Dm.jpg"
    }, {
        "adult": false,
        "credit_id": "638c5aaa7d5db50fdd12463a",
        "department": "Crew",
        "gender": 2,
        "id": 3814629,
        "job": "Stunts",
        "known_for_department": "Acting",
        "name": "Finn McCager Higgins",
        "original_name": "Finn McCager Higgins",
        "popularity": 0.994,
        "profile_path": "/nWvzmUc3xkh6dJTPgmkHc7OHJk7.jpg"
    }],
    "id": 917007
};

const movieDetails = {
    "adult": false,
    "backdrop_path": "/zPcuuhwZFDzBTc66wtrLZ2qX5y4.jpg",
    "belongs_to_collection": {
        "backdrop_path": "/6kh59mZizZsttZPR0HAdXk6Ve2n.jpg",
        "id": 84,
        "name": "Indiana Jones Collection",
        "poster_path": "/lpxDrACKJhbbGOlwVMNz5YCj6SI.jpg"
    },
    "budget": 295000000,
    "genres": [{"id": 12, "name": "Adventure"}, {"id": 28, "name": "Action"}],
    "homepage": "https://movies.disney.com/indiana-jones-and-the-dial-of-destiny",
    "id": 335977,
    "imdb_id": "tt1462764",
    "original_language": "en",
    "original_title": "Indiana Jones and the Dial of Destiny",
    "overview": "Finding himself in a new era, approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
    "popularity": 507.767,
    "poster_path": "/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
    "production_companies": [{
        "id": 1,
        "logo_path": "/o86DbpburjxrqAzEDhXZcyE8pDb.png",
        "name": "Lucasfilm Ltd.",
        "origin_country": "US"
    }],
    "production_countries": [{"iso_3166_1": "US", "name": "United States of America"}],
    "release_date": "2023-06-28",
    "revenue": 0,
    "runtime": 154,
    "spoken_languages": [{"english_name": "English", "iso_639_1": "en", "name": "English"}],
    "status": "Released",
    "tagline": "A legend will face his destiny.",
    "title": "Indiana Jones and the Dial of Destiny",
    "video": false,
    "vote_average": 6.504,
    "vote_count": 114
}

const personDetails = {
    "adult": false,
    "also_known_as": [],
    "biography": "From Wikipedia, the free encyclopediaDamon Herriman (born 31 March 1970) is an Australian actor and writer. He is known for his film and television work in Australia and the United States. He is perhaps best known for his portrayal of Dewey Crowe in Justified. In 2019, he portrayed the cult leader and criminal Charles Manson in both the Netflix series Mindhunter and in the Quentin Tarantino film Once Upon a Time in Hollywood.Description above from the Wikipedia article Damon Herriman, licensed under CC-BY-SA, full list of contributors on Wikipedia",
    "birthday": "1970-03-31",
    "deathday": null,
    "gender": 2,
    "homepage": "https://lmcm.com.au/artists/damon-herriman/",
    "id": 62752,
    "imdb_id": "nm0380632",
    "known_for_department": "Acting",
    "name": "Damon Herriman",
    "place_of_birth": "Adelaide, South Australia, Australia",
    "popularity": 15.069,
    "profile_path": "/6Wb5q2nua0JGJRdtZLRBon6uAua.jpg"
}

const personMovies = {
    "cast": [{
        "adult": false,
        "backdrop_path": null,
        "character": "Fanny Cradock",
        "credit_id": "53409b8c0e0a2679ad000bb0",
        "genre_ids": [Array],
        "id": 157917,
        "order": 0,
        "original_language": "en",
        "original_title": "Fear of Fanny",
        "overview": "The bizarre tale of Fanny Cradock, Britain's famous and maligned TV chef from 50s to the 70s.",
        "popularity": 3.018,
        "poster_path": "/6es50XIfvlS893dahdfSCDm2kfe.jpg",
        "release_date": "2006-10-23",
        "title": "Fear of Fanny",
        "video": false,
        "vote_average": 7.3,
        "vote_count": 6
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Daphne Cauldwell",
        "credit_id": "570a84bfc3a3680fc2003f3e",
        "genre_ids": [Array],
        "id": 392261,
        "order": 0,
        "original_language": "en",
        "original_title": "Bad Sugar",
        "overview": "A dysfunctional, wealthy mining dynasty, with an ailing patriarch and some greedy siblings. A peculiarly British take on telenovela style melodramas, played for laughs.",
        "popularity": 0.6,
        "poster_path": null,
        "release_date": "2012-08-26",
        "title": "Bad Sugar",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Mother",
        "credit_id": "5b79efc2c3a36860df03a2f5",
        "genre_ids": [Array],
        "id": 543358,
        "order": 0,
        "original_language": "en",
        "original_title": "The Bird",
        "overview": "A young man spends his days desperate to garner the attention of his emotionally absent mother who is only interested in caring for a visiting starling.",
        "popularity": 0.6,
        "poster_path": "/wyLLIJ2eTHqHEXFl5UYmOPYLkQI.jpg",
        "release_date": "2014-04-13",
        "title": "The Bird",
        "video": false,
        "vote_average": 7,
        "vote_count": 1
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Gail Sinclair",
        "credit_id": "5e0e09e612c60400143f8519",
        "genre_ids": [Array],
        "id": 660092,
        "order": 0,
        "original_language": "en",
        "original_title": "Morning Has Broken",
        "overview": "Morning Has Broken sees Julie Davis play a monstrous presenter struggling to cope with the decline of her show",
        "popularity": 0.6,
        "poster_path": null,
        "release_date": "2014-07-10",
        "title": "Morning Has Broken",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Ruth",
        "credit_id": "52fe4551c3a368484e0532b7",
        "genre_ids": [Array],
        "id": 27531,
        "order": 1,
        "original_language": "en",
        "original_title": "AD/BC: A Rock Opera",
        "overview": "An all-singing, all-dancing, star-spangled musical leap around the biblical story of the Nativity, set in 1972. With a comic twist, this familiar story is brought to life through the eyes of the innkeeper. Despairing after a bad year, he contemplates suicide but his attempt is stalled by a voice from above who points out that King Herod is coming to town.",
        "popularity": 3.083,
        "poster_path": "/2loWHloYY5mHVgZcaZD2Iblpnel.jpg",
        "release_date": "2004-12-21",
        "title": "AD/BC: A Rock Opera",
        "video": false,
        "vote_average": 6.1,
        "vote_count": 25
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Mother",
        "credit_id": "536ce1df0e0a2647c400dd03",
        "genre_ids": [Array],
        "id": 268910,
        "order": 1,
        "original_language": "en",
        "original_title": "For the Love of God",
        "overview": "'For the Love of God' is the wickedly irreverent tale of Graham (Coogan); an over-grown man-child still living at home under the suffocating glare of his elderly Mother, in her dusty and forgotten Christian bookshop.  Graham has a terrible secret - an unholy fantasy - which only he and his Mother's pet Jackdaw (McKellen) know about.  Spurred on by the sinister bird and the possibility of consummating his perverse desire, will Graham do the deed before his Mother uncovers the awful truth?",
        "popularity": 1.697,
        "poster_path": null,
        "release_date": "2007-02-28",
        "title": "For the Love of God",
        "video": false,
        "vote_average": 4,
        "vote_count": 2
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Lizzie/Faith",
        "credit_id": "55d313a692514170b1000f8b",
        "genre_ids": [Array],
        "id": 355072,
        "order": 1,
        "original_language": "en",
        "original_title": "Lizzie and Sarah",
        "overview": "Lizzie and Sarah are two fiftysomething suburban housewives, perpetually mistreated and ignored by unloving, selfish husbands. The highlight of their otherwise dull lives is their role in an amateur dramatic society, The Borking Players. In the aftermath of a tragic accident which causes the death of a popular local teenager, emotions run high, and following a dismal birthday lunch for Sarah, the two friends embark on a spur-of-the-moment shopping trip. As the day unfolds, they find a way to wreak their revenge.",
        "popularity": 1.073,
        "poster_path": null,
        "release_date": "2010-03-20",
        "title": "Lizzie and Sarah",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 3
    }, {
        "adult": false,
        "backdrop_path": "/dahCodt1JcRT4ksvxbJH4vsksDu.jpg",
        "character": "Deb",
        "credit_id": "613b3f0707faa2002a5eb2c0",
        "genre_ids": [Array],
        "id": 863747,
        "order": 1,
        "original_language": "en",
        "original_title": "The Clearing",
        "overview": "Battling against the wilderness and his own ego, Bill struggles to impress Deb with below-par outdoor skills and shocking behaviour, until their last-ditch camping trip takes a sinister turn.",
        "popularity": 0.655,
        "poster_path": "/cIQQwI3AA8XS40AcjQEMNZgEUty.jpg",
        "release_date": "2021-09-30",
        "title": "The Clearing",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/yATuNOVifq933nYIqHX9LNp83Vx.jpg",
        "character": "Narrator",
        "credit_id": "6358a54f2cefc2009863f40b",
        "genre_ids": [Array],
        "id": 1040159,
        "order": 1,
        "original_language": "en",
        "original_title": "My Massive Cock",
        "overview": "An extra-large penis is an object of desire for many. But for some men, extra-large seriously complicates their lives and relationships, and penis reduction surgery seems the only answer.",
        "popularity": 8.203,
        "poster_path": "/9JQHViS8uugeWKfFsnEj3xTB2dZ.jpg",
        "release_date": "2022-10-24",
        "title": "My Massive Cock",
        "video": false,
        "vote_average": 5.5,
        "vote_count": 4
    }, {
        "adult": false,
        "backdrop_path": "/txFk9t1ReGf0Iv44RA7yRsrzDVB.jpg",
        "character": "",
        "credit_id": "56467de39251413acc000ef4",
        "genre_ids": [Array],
        "id": 58307,
        "order": 2,
        "original_language": "en",
        "original_title": "Steve Coogan: The Man Who Thinks He's It",
        "overview": "Recorded live at The Palace Theatre in Manchester. All his favourite characters appear - Alan Partridge, Paul and Pauline Calf, Tony Ferrino, Ernest Moss and the irritating Duncan Thicket.",
        "popularity": 2.377,
        "poster_path": "/fkzM3acR2tWmCc0uAFR0r7UE9Bp.jpg",
        "release_date": "1999-10-01",
        "title": "Steve Coogan: The Man Who Thinks He's It",
        "video": false,
        "vote_average": 6.9,
        "vote_count": 7
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Mrs. Goodington",
        "credit_id": "588cd7ce9251410a4a002964",
        "genre_ids": [Array],
        "id": 437797,
        "order": 2,
        "original_language": "en",
        "original_title": "Uncle Wormsley's Christmas",
        "overview": "Uncle Wormsley is a grey, decaying old man with cobweb-like hair and rotten fingernails. A lone figure who keeps himself to himself, Wormsley's only friend is a monstrous crab called Crabsley, who lives in a dungeon under his house.",
        "popularity": 0.779,
        "poster_path": "/19ONnOBjm2gphgPPF9eXaCifx9V.jpg",
        "release_date": "2012-12-25",
        "title": "Uncle Wormsley's Christmas",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/2a5JDYRCD49ihvozEerkRamz4lU.jpg",
        "character": "Self",
        "credit_id": "57279f91c3a3681da2000645",
        "genre_ids": [Array],
        "id": 183983,
        "order": 3,
        "original_language": "en",
        "original_title": "Steve Coogan: The Inside Story",
        "overview": "Spoof documentary about the career of comedian Steve Coogan.",
        "popularity": 1.049,
        "poster_path": "/sWElyWB5Aq4kQwDK5PwmzWr6JqE.jpg",
        "release_date": "2009-12-27",
        "title": "Steve Coogan: The Inside Story",
        "video": false,
        "vote_average": 6.3,
        "vote_count": 3
    }, {
        "adult": false,
        "backdrop_path": "/9OnrpIpTfsgXYHkCpeHDJs0Lm7B.jpg",
        "character": "Herself",
        "credit_id": "5d60636d924ce527b714c1b8",
        "genre_ids": [Array],
        "id": 73787,
        "order": 3,
        "original_language": "en",
        "original_title": "The Mighty Boosh: Journey of the Childmen",
        "overview": "Shot during the mammoth Future Sailors tour, this intimate film observes the comic genius of the Mighty Boosh as they navigate a nation hooked on its cult.",
        "popularity": 1.268,
        "poster_path": "/bHuF2qduqZWafVRol9zey1ePlTY.jpg",
        "release_date": "2010-11-15",
        "title": "The Mighty Boosh: Journey of the Childmen",
        "video": false,
        "vote_average": 8,
        "vote_count": 1
    }, {
        "adult": false,
        "backdrop_path": "/37LyKFPr7ksoXMea7MIWFa8Llaj.jpg",
        "character": "Gail",
        "credit_id": "645dc3999590e301222810be",
        "genre_ids": [Array],
        "id": 714669,
        "order": 3,
        "original_language": "en",
        "original_title": "Run Rabbit Run",
        "overview": "Sarah is a fertility doctor with a firm understanding of the cycle of life. When she is forced to make sense of the increasingly strange behavior of her young daughter Mia, she must challenge her own beliefs and confront a ghost from her past.",
        "popularity": 25.474,
        "poster_path": "/n34lYVoFy1C2lc02i7eaZFWznuN.jpg",
        "release_date": "2023-01-19",
        "title": "Run Rabbit Run",
        "video": false,
        "vote_average": 6.05,
        "vote_count": 30
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Dee",
        "credit_id": "57279fb19251416dfb001c32",
        "genre_ids": [Array],
        "id": 98905,
        "order": 4,
        "original_language": "en",
        "original_title": "Come on Eileen",
        "overview": "One summer, mother and ex dancer Eileen lapses back to a troubled past as she starts a new relationship... we watch as she and her family combust. The film, shot on a micro budget, treads between darkness and humour as it moves from its beginning in the suburban cricket club to its conclusion at a music festival.",
        "popularity": 1.875,
        "poster_path": null,
        "release_date": "2010-10-06",
        "title": "Come on Eileen",
        "video": false,
        "vote_average": 6.7,
        "vote_count": 3
    }, {
        "adult": false,
        "backdrop_path": "/gg2YrudhsH6zAOpnPKxj3VREZQY.jpg",
        "character": "Livy",
        "credit_id": "5745ea4f92514127cb000971",
        "genre_ids": [Array],
        "id": 399226,
        "order": 4,
        "original_language": "en",
        "original_title": "Brakes",
        "overview": "Brakes is a dark, improv-based ensemble comedy set in London. Divided into two parts, it tells the story of each couple's relationship in reverse, starting with the break-ups.",
        "popularity": 1.8,
        "poster_path": "/oBd1UiFPuKoNBTdhoKYYo9BaONS.jpg",
        "release_date": "2017-11-24",
        "title": "Brakes",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 9
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Herself/Lizzie",
        "credit_id": "5a3bbd780e0a264cbe21f2aa",
        "genre_ids": [Array],
        "id": 493933,
        "order": 4,
        "original_language": "en",
        "original_title": "The Angina Monologues",
        "overview": "Victoria Wood takes to the stage with an all female bill for a night of comedy in support of The British Heart Foundation to help raise awareness of heart disease in women.",
        "popularity": 2.882,
        "poster_path": null,
        "release_date": "2010-12-10",
        "title": "The Angina Monologues",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/2bCcbNyB1g5F8CXqABo0JsNig73.jpg",
        "character": "Moira",
        "credit_id": "52fe4220c3a36847f8005dc1",
        "genre_ids": [Array],
        "id": 156,
        "order": 5,
        "original_language": "da",
        "original_title": "Wilbur begår selvmord",
        "overview": "The strange comedy film of two close brothers; one, Wilbur, who wants to kill himself, and the other, Harbour, who tries to prevent this. When their father dies leaving them his bookstore they meet a woman who makes their lives a bit better yet with a bit more trouble as well.",
        "popularity": 4.525,
        "poster_path": "/bRrHJbr8kMb849IKBZ0RBk2Vmte.jpg",
        "release_date": "2002-11-08",
        "title": "Wilbur Wants to Kill Himself",
        "video": false,
        "vote_average": 6.5,
        "vote_count": 77
    }, {
        "adult": false,
        "backdrop_path": "/wYuuvNzIcQPKGoK03JgPZ2IkB0A.jpg",
        "character": "Elizabeth Elliot",
        "credit_id": "52fe45b99251416c75060441",
        "genre_ids": [Array],
        "id": 13949,
        "order": 5,
        "original_language": "en",
        "original_title": "Persuasion",
        "overview": "Royal Navy captain Wentworth was haughtily turned down eight years ago as suitor of pompous baronet Sir Walter Elliot's daughter Anne, despite true love. Now he visits their former seaside country estate, rented by his brother-in-law, admiral Croft, so the financially stressed baronet can afford a fashionable, cheaper residence in trendy Bath. First the former lovers meet again on the estate, where they feel vibes again, but neither dares admit them until it seems too late.",
        "popularity": 11.857,
        "poster_path": "/p0SAkCFD02wj2gekOvFilMjzs3j.jpg",
        "release_date": "2007-04-01",
        "title": "Persuasion",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 253
    }, {
        "adult": false,
        "backdrop_path": "/b3iXdHZoNlEAhOWTDjbIqNGn5qy.jpg",
        "character": "Shelley",
        "credit_id": "59321765c3a3685a0b002b80",
        "genre_ids": [Array],
        "id": 13371,
        "order": 5,
        "original_language": "en",
        "original_title": "Sex Lives of the Potato Men",
        "overview": "Two lowlifes with active fantasy sex lives deliver potatoes to various restaurants and grocers.",
        "popularity": 4.309,
        "poster_path": "/vpVrjh8r9KcrkgsgChFNQi3aZmX.jpg",
        "release_date": "2004-02-20",
        "title": "Sex Lives of the Potato Men",
        "video": false,
        "vote_average": 4.7,
        "vote_count": 26
    }, {
        "adult": false,
        "backdrop_path": "/gdXOVGtPfiYvBUTl1d687dUi82O.jpg",
        "character": "Sally",
        "credit_id": "5892a1ddc3a3680b10001d3d",
        "genre_ids": [Array],
        "id": 61528,
        "order": 6,
        "original_language": "en",
        "original_title": "Born Equal",
        "overview": "Four characters living in one neighborhood in London - all living dramatically different lives, all of them on the edge - see their stories unfold.",
        "popularity": 2.872,
        "poster_path": "/iEN4zUoqw6Fz7MMwXtUihQLDitC.jpg",
        "release_date": "2006-12-04",
        "title": "Born Equal",
        "video": false,
        "vote_average": 5.1,
        "vote_count": 8
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Kissy Sturnevan",
        "credit_id": "60ca9afec5ada50040371494",
        "genre_ids": [Array],
        "id": 338969,
        "order": 6,
        "original_language": "en",
        "original_title": "The Toxic Avenger",
        "overview": "After a terminally-ill janitor attempts to rob the company he works for, following his greedy employer's refusal to pay for his treatment, he falls into a vat of toxic waste, becoming a deformed superhero who seeks to protect his son and community while getting back at those who wronged him.",
        "popularity": 2.896,
        "poster_path": null,
        "release_date": "",
        "title": "The Toxic Avenger",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/mdamlb1wa58WzfOIzyDcbdkDarT.jpg",
        "character": "Felicity",
        "credit_id": "645a480a77d23b00fccb7ee3",
        "genre_ids": [Array],
        "id": 1124514,
        "order": 6,
        "original_language": "en",
        "original_title": "The Understudy",
        "overview": "An acting understudy eventually assumes center stage, but at a price.",
        "popularity": 0.6,
        "poster_path": "/uIdKgEXnk7l5XQ3YlaLtHJBpojU.jpg",
        "release_date": "2014-03-05",
        "title": "The Understudy",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/kT8VRai0b8WaEx6WLpE8RvC0bBe.jpg",
        "character": "Alice",
        "credit_id": "56674996c3a36808ec001c22",
        "genre_ids": [Array],
        "id": 37495,
        "order": 7,
        "original_language": "en",
        "original_title": "Four Lions",
        "overview": "A group of Muslim men living in Sheffield hatch an inept plan to become suicide bombers.",
        "popularity": 12.866,
        "poster_path": "/lU9WFPChJ1CsD5kZuYoCdoAlbRd.jpg",
        "release_date": "2010-05-07",
        "title": "Four Lions",
        "video": false,
        "vote_average": 6.974,
        "vote_count": 1000
    }, {
        "adult": false,
        "backdrop_path": "/1OuzyjCpcoiu4iX2a9s03awTH4h.jpg",
        "character": "(voice)",
        "credit_id": "52fe4c2fc3a36847f8221be5",
        "genre_ids": [Array],
        "id": 160324,
        "order": 8,
        "original_language": "en",
        "original_title": "Hello, Friend",
        "overview": "A satirical look at modern technology.",
        "popularity": 0.697,
        "poster_path": "/ne1T88WvBtPeCmKHoXofF64unKu.jpg",
        "release_date": "2003-02-02",
        "title": "Hello, Friend",
        "video": false,
        "vote_average": 6.9,
        "vote_count": 11
    }, {
        "adult": false,
        "backdrop_path": "/vpRMzPqHC03I7hPPET4Av2OT8dI.jpg",
        "character": "Lady Baltimore",
        "credit_id": "59ee0b4fc3a36871bc0297a4",
        "genre_ids": [Array],
        "id": 400617,
        "order": 8,
        "original_language": "en",
        "original_title": "Phantom Thread",
        "overview": "In 1950s London, renowned British dressmaker Reynolds Woodcock comes across Alma, a young, strong-willed woman, who soon becomes ever present in his life as his muse and lover.",
        "popularity": 18.441,
        "poster_path": "/hgoWjp9Sh0MI97eAMZCnIoVfgvq.jpg",
        "release_date": "2017-12-25",
        "title": "Phantom Thread",
        "video": false,
        "vote_average": 7.302,
        "vote_count": 3146
    }, {
        "adult": false,
        "backdrop_path": "/yamT0hdutYG7HDFHei49zeIFyVR.jpg",
        "character": "Mrs. Taylor",
        "credit_id": "52fe460c9251416c910475a1",
        "genre_ids": [Array],
        "id": 36801,
        "order": 10,
        "original_language": "en",
        "original_title": "Cemetery Junction",
        "overview": "In 1970s England, three blue-collar friends spend their days joking, drinking, fighting and chasing girls. Freddie wants to leave their working-class world but cool, charismatic Bruce and lovable loser Snork are happy with life the way it is. When Freddie gets a new job as a door-to-door salesman and bumps into his old school sweetheart Julie, the gang are forced to make choices that will change their lives for ever.",
        "popularity": 6.556,
        "poster_path": "/x5ItIOSRFzi2huaT3ceNJLK6M1w.jpg",
        "release_date": "2010-04-14",
        "title": "Cemetery Junction",
        "video": false,
        "vote_average": 6.6,
        "vote_count": 252
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Dawn Sutcliffe",
        "credit_id": "646a2908c3514c0100fe7fb8",
        "genre_ids": [Array],
        "id": 1063636,
        "order": 10,
        "original_language": "en",
        "original_title": "Gavin & Stacey Christmas Special",
        "overview": "Nessa and the Wests head east, with some help from Dave and his coach. Meanwhile in Essex, Dawn and Pete visit for drinks, Mick is preoccupied with his new love, and Smithy cannot wait to spend his first Christmas with Neil the Baby. Pam has prepared a lovely spread and Bryn has his mistletoe ready, but as the Christmas spirit gets a grip, Gavin and Stacey have a startling announcement to make.",
        "popularity": 0.995,
        "poster_path": "/hlWwzWFmQ3okk52PlA4nrTTer1K.jpg",
        "release_date": "2008-12-25",
        "title": "Gavin & Stacey Christmas Special",
        "video": false,
        "vote_average": 9,
        "vote_count": 2
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Self",
        "credit_id": "52fe44729251416c91010ffb",
        "genre_ids": [Array],
        "id": 31301,
        "order": 11,
        "original_language": "en",
        "original_title": "The Secret Policeman's Ball: The Ball in the Hall",
        "overview": "The rebirth of Amnesty International's legendary SECRET POLICEMAN'S BALL at the Royal Albert Hall on 14th October - after a 15 year hiatus - was a resounding success. Bigger, Better and Ballsier than ever before, 'The Ball In The Hall' is a non-stop, rapid-fire, relentless smorgasbord of comedy and music.  6,000 people turned up to create a fantastic atmosphere as some of the best contemporary comic and music talent from both sides of the Atlantic delivered one show-stopping performance after another. Featuring never-before-seen collaborations, brand new sketches, explosive stand-up, off-stage performances, surprise ingredients and an anthem for the world, there has been nothing like it in the comedy world for years.",
        "popularity": 2.389,
        "poster_path": null,
        "release_date": "2006-10-31",
        "title": "The Secret Policeman's Ball: The Ball in the Hall",
        "video": false,
        "vote_average": 6.7,
        "vote_count": 3
    }, {
        "adult": false,
        "backdrop_path": "/j1phFR0pMwqouyyvN8g3qjqJi8O.jpg",
        "character": "Insinuating Wife",
        "credit_id": "57e01906925141059c003e76",
        "genre_ids": [Array],
        "id": 32577,
        "order": 12,
        "original_language": "en",
        "original_title": "The Parole Officer",
        "overview": "A hapless parole officer is framed for murder by a crooked police chief. To prove his innocence he must entice his former clients away from the law abiding lives they are now living to recover the evidence that will save him.",
        "popularity": 7.777,
        "poster_path": "/tTiBD7kCwIpjOXZ0L2JDMNo4su5.jpg",
        "release_date": "2001-08-10",
        "title": "The Parole Officer",
        "video": false,
        "vote_average": 5.9,
        "vote_count": 85
    }, {
        "adult": false,
        "backdrop_path": "/mYKP6qcDUimVMAHQWLOuDHjO19S.jpg",
        "character": "Daphne",
        "credit_id": "5c6b2b849251412a74ff5339",
        "genre_ids": [Array],
        "id": 445629,
        "order": 13,
        "original_language": "en",
        "original_title": "Fighting with My Family",
        "overview": "Born into a tight-knit wrestling family, Paige and her brother Zak are ecstatic when they get the once-in-a-lifetime opportunity to try out for the WWE. But when only Paige earns a spot in the competitive training program, she must leave her loved ones behind and face this new cutthroat world alone. Paige's journey pushes her to dig deep and ultimately prove to the world that what makes her different is the very thing that can make her a star.",
        "popularity": 21.037,
        "poster_path": "/cVhe15rJLRjolunSWLBN6xQLyGU.jpg",
        "release_date": "2019-02-14",
        "title": "Fighting with My Family",
        "video": false,
        "vote_average": 6.859,
        "vote_count": 1523
    }, {
        "adult": false,
        "backdrop_path": "/wIzdeptg5ZARpgCsj2Hvw94pYuu.jpg",
        "character": "Counsellor",
        "credit_id": "52fe43299251416c75005dd7",
        "genre_ids": [Array],
        "id": 10111,
        "order": 14,
        "original_language": "en",
        "original_title": "Confetti",
        "overview": "A mockumentary that follows three couples as they battle it out to win the coveted title of 'Most Original Wedding of the Year'.",
        "popularity": 6.94,
        "poster_path": "/5lEkehJivH5anJXY8oP1RImBfnQ.jpg",
        "release_date": "2006-05-05",
        "title": "Confetti",
        "video": false,
        "vote_average": 5.8,
        "vote_count": 52
    }, {
        "adult": false,
        "backdrop_path": "/6mJrgL7Mi13XjJeGYJFlD6UEVQw.jpg",
        "character": "Linda Le Bon (voice)",
        "credit_id": "61c3e00121621d006474ff7b",
        "genre_ids": [Array],
        "id": 438695,
        "order": 18,
        "original_language": "en",
        "original_title": "Sing 2",
        "overview": "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
        "popularity": 147.598,
        "poster_path": "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
        "release_date": "2021-12-01",
        "title": "Sing 2",
        "video": false,
        "vote_average": 7.941,
        "vote_count": 3757
    }, {
        "adult": false,
        "backdrop_path": null,
        "character": "Interviewee – Actor",
        "credit_id": "6466b8c3d1857201207fd8d5",
        "genre_ids": [Array],
        "id": 1128734,
        "order": 19,
        "original_language": "en",
        "original_title": "Appointment with Dr. Terrible",
        "overview": "A behind-the-scenes documentary on the making of \"Dr. Terrible's House of Horrible\" featuring Steve Coogan.",
        "popularity": 0.633,
        "poster_path": "/eIZtJwYl918KhoWQ5eim8pqfUS8.jpg",
        "release_date": "2003-08-04",
        "title": "Appointment with Dr. Terrible",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": "/xUWf5xX0AnZgAnYXAMk03zTbsef.jpg",
        "character": "Nancy the caterer",
        "credit_id": "63a30b8d4f33ad008c025289",
        "genre_ids": [Array],
        "id": 508,
        "order": 30,
        "original_language": "en",
        "original_title": "Love Actually",
        "overview": "Eight London couples try to deal with their relationships in different ways. Their tryst with love makes them discover how complicated relationships can be.",
        "popularity": 21.83,
        "poster_path": "/7QPeVsr9rcFU9Gl90yg0gTOTpVv.jpg",
        "release_date": "2003-09-07",
        "title": "Love Actually",
        "video": false,
        "vote_average": 7.102,
        "vote_count": 5955
    }, {
        "adult": false,
        "backdrop_path": "/i7W7x1EhLk0PXXFnHiCPBgUjBVC.jpg",
        "character": "UNFITA OPS (voice)",
        "credit_id": "58558a6fc3a36827a503df69",
        "genre_ids": [Array],
        "id": 51052,
        "order": 43,
        "original_language": "en",
        "original_title": "Arthur Christmas",
        "overview": "This movie reveals the incredible, never-before seen answer to every child's question: \"So how does Santa deliver all those presents in one night?\" The answer: Santa's (Jim Broadbent's) exhilarating, ultra-high-tech operation hidden beneath the North Pole. But at the center of this movie is a story about a family in a state of comic dysfunction and an unlikely hero, Arthur (James McAvoy), with an urgent mission that must be completed before Christmas morning dawns.",
        "popularity": 18.957,
        "poster_path": "/sPCrGLdTMn0ud3oAJG37VDxpQfZ.jpg",
        "release_date": "2011-11-10",
        "title": "Arthur Christmas",
        "video": false,
        "vote_average": 6.764,
        "vote_count": 1280
    }, {
        "adult": false,
        "backdrop_path": "/ysUbm8qcKLaUiMf0H82mE5ujvVQ.jpg",
        "character": "News Reporter (voice) (uncredited)",
        "credit_id": "5baa366dc3a36839fe018663",
        "genre_ids": [Array],
        "id": 747,
        "order": 55,
        "original_language": "en",
        "original_title": "Shaun of the Dead",
        "overview": "Shaun lives a supremely uneventful life, which revolves around his girlfriend, his mother, and, above all, his local pub. This gentle routine is threatened when the dead return to life and make strenuous attempts to snack on ordinary Londoners.",
        "popularity": 32.138,
        "poster_path": "/dgXPhzNJH8HFTBjXPB177yNx6RI.jpg",
        "release_date": "2004-04-09",
        "title": "Shaun of the Dead",
        "video": false,
        "vote_average": 7.5,
        "vote_count": 7578
    }],
    "crew": [{
        "adult": false,
        "backdrop_path": null,
        "credit_id": "62fb79c01dbc88007f2e39df",
        "department": "Directing",
        "genre_ids": [Array],
        "id": 1013436,
        "job": "Director",
        "original_language": "en",
        "original_title": "Russian Media Monitor",
        "overview": "Creator, Producer, Director, Screenwriter Julia Davis, chronicles Vladimir Putin's rise and fall historically, and tallies the score on the world stage in regard to Russia's waging war, disinformation and Cyberwarfare participation.",
        "popularity": 3.909,
        "poster_path": "/69oDDeniX7acg09ugNP4XA30VZp.jpg",
        "release_date": "2023-06-15",
        "title": "Russian Media Monitor",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    }, {
        "adult": false,
        "backdrop_path": null,
        "credit_id": "57d4b5e692514160a2009229",
        "department": "Production",
        "genre_ids": [Array],
        "id": 415289,
        "job": "Line Producer",
        "original_language": "en",
        "original_title": "Lima: Breaking the Silence",
        "overview": "An intense drama based on the true story of Peruvian rebels who in 1997 kidnapped several hundred high-ranking diplomats and government officials in an attempt to force the release of 400 political prisoners.",
        "popularity": 1.96,
        "poster_path": "/vAonXrlsXGtY4LNdGjn0JUHfvi9.jpg",
        "release_date": "1999-03-30",
        "title": "Lima: Breaking the Silence",
        "video": false,
        "vote_average": 5.3,
        "vote_count": 3
    }, {
        "adult": false,
        "backdrop_path": null,
        "credit_id": "55d31447c3a368479e000857",
        "department": "Writing",
        "genre_ids": [Array],
        "id": 355072,
        "job": "Writer",
        "original_language": "en",
        "original_title": "Lizzie and Sarah",
        "overview": "Lizzie and Sarah are two fiftysomething suburban housewives, perpetually mistreated and ignored by unloving, selfish husbands. The highlight of their otherwise dull lives is their role in an amateur dramatic society, The Borking Players. In the aftermath of a tragic accident which causes the death of a popular local teenager, emotions run high, and following a dismal birthday lunch for Sarah, the two friends embark on a spur-of-the-moment shopping trip. As the day unfolds, they find a way to wreak their revenge.",
        "popularity": 1.073,
        "poster_path": null,
        "release_date": "2010-03-20",
        "title": "Lizzie and Sarah",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 3
    }, {
        "adult": false,
        "backdrop_path": "/62vFam8movRl3jf1ZyM9sPT7GwM.jpg",
        "credit_id": "62a61bdd596a9100665ae1c6",
        "department": "Writing",
        "genre_ids": [Array],
        "id": 935516,
        "job": "Writer",
        "original_language": "en",
        "original_title": "Nude Tuesday",
        "overview": "When middle-aged suburban couple, Laura and Bruno are gifted a remote couples’ retreat for their anniversary, they decide to give their failing marriage one last shot before calling it quits. Arriving in an idyllic sanctuary nestled in the mountains, Laura and Bruno uncomfortably enter a world of laughter workshops, tantric dance, sexual liberation and emotional animals, helmed by the charismatic guru Bjorg Rassmussen. When new temptations start to take hold, the couple are pushed to the brink forcing them to look within to find what they really want. But will they bare all to get it?",
        "popularity": 3.263,
        "poster_path": "/rWkhNu84tmHMokywg3LgPRVtwOl.jpg",
        "release_date": "2022-06-23",
        "title": "Nude Tuesday",
        "video": false,
        "vote_average": 4.8,
        "vote_count": 12
    }],
    "id": 1836
};
